name: "Stale issues and pull requests"
on:
  schedule:
  - cron: "40 17 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 5
        exempt-issue-label: 'needs-triage'
        exempt-pr-label: 'needs-triage'
        operations-per-run: 100
        stale-issue-label: 'stale'
        stale-issue-message: |
          'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 5 days'

          If this issue was automatically closed and you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thank you!
        stale-pr-label: 'stale'
        stale-pr-message: |
          Marking this pull request as stale due to inactivity. This helps our maintainers find and focus on the active pull requests. If this pull request receives no comments in the next 30 days it will automatically be closed. Maintainers can also remove the stale label.

          If this pull request was automatically closed and you feel this pull request should be reopened, we encourage creating a new pull request linking back to this one for added context. Thank you!
